### PR TITLE
US-919: Added axios and custom useHttpGet hook

### PR DESCRIPTION
**Pull request by jmiller-nexient**
There's more work that can be done to the custom hook and tests to make it "enterprise grade" but I don't see the point of spending more time on it now.  I was able to verify it by mimicking calls through the UI.  Lots to learn about testing code like this but we can deal with that and any issues with this implementation as they come up.  For now, I wanted to crawl out of the rabbit hole and move forward.

### CODE REVIEW

**Comment by jmiller-nexient** [comment]
> in the useEffect hook we need to pass an empty array as a 2nd parameter to the callback because without it when the state changes and cause a re-render the useEffect will be implemented again and goes for an infinite loop this way

You didn't comment inline with the code so I'm assuming you are referring to the useEffect in useHttpGet.  In that case, you are incorrect.  There's already two triggers defined that constrain when useEffect runs. See line 65 in that file.

**Comment by GaberMowiena** [comment]
> > in the useEffect hook we need to pass an empty array as a 2nd parameter to the callback because without it when the state changes and cause a re-render the useEffect will be implemented again and goes for an infinite loop this way
> 
> You didn't comment inline with the code so I'm assuming you are referring to the useEffect in useHttpGet. In that case, you are incorrect. There's already two triggers defined that constrain when useEffect runs. See line 65 in that file.

**Comment by GaberMowiena** [comment]
Yeah! you are right - Nevermind :)

**Comment by JeremySparkman** [comment]
When I run the Jest tests one of the tests is failing. 
"app/hooks/useHttpGet/tests/index.test.tsx:4:33 - error TS2307: Cannot find module '@testing-library/react"
We're also lacking a lot of coverage for the new files.

**Comment by jmiller-nexient** [comment]
> I'm unable to get this to run. When I do npm run start I get an error that react-app-polyfill/ie11 cannot be found. When I run npm install I get a whole host of errors around npm being unable to find certain files.

run 'npm install" to install the missing package.

**Comment by jmiller-nexient** [comment]
> When I run the Jest tests one of the tests is failing.
> "app/hooks/useHttpGet/tests/index.test.tsx:4:33 - error TS2307: Cannot find module '@testing-library/react"
> Update: I removed my old node_modules and tried to npm install and I'm also getting the same errors as @astoneDTE
> We're also lacking a lot of coverage for the new files.

All I had to do to resolve the issue with the polyfill package was run 'npm install'.  That should also take care of the react-testing-library requirement.  You pretty much have to run that command anytime there's a changes to the package-lock.json file.

**Comment by astoneDTE** [comment]
> > I'm unable to get this to run. When I do npm run start I get an error that react-app-polyfill/ie11 cannot be found. When I run npm install I get a whole host of errors around npm being unable to find certain files.
> 
> run 'npm install" to install the missing package.

npm install is still erroring out for me.

`npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /Users/astone/Builds/DTE/WISMO/wismo/node_modules/.staging/cross-env-c86a92b3/node_modules/rimraf
npm ERR! dest /Users/astone/Builds/DTE/WISMO/wismo/node_modules/.staging/rimraf-19456ac2
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/astone/Builds/DTE/WISMO/wismo/node_modules/.staging/cross-env-c86a92b3/node_modules/rimraf' -> '/Users/astone/Builds/DTE/WISMO/wismo/node_modules/.staging/rimraf-19456ac2'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`

**Pull request merged**
